default:
    image: kennethreitz/pipenv

stages:
    - build
    - check
    - test

build:
    stage: build
    cache:
        paths:
            - ~/.local/share/virtualenvs/
    script:
        - pipenv sync
