default:
    image: archlinux

stages:
    - setup
    - build
    - check
    - test

setup:
    stage: setup
    cache:
        paths:
            - /*
    script:
        - pacman --noconfirm -Sy python-pipenv

build:
    stage: build
    script:
        - pwd
        - ls -lAh
