image: kennethreitz/pipenv

variables:
    PYTHONPATH: "$CI_PROJECT_DIR/src:$PYTHONPATH"
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/cache/.cache/"
    XDG_DATA_HOME: "$CI_PROJECT_DIR/cache/.local/share/"

cache:
    # Cache per branch
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - cache/

stages:
    - build
    - check
    - test

build:
    stage: build
    script:
        - pipenv clean
        - pipenv sync --dev

check:
    stage: check
    script:
        - pipenv run python setup.py check

test:
    stage: test
    script:
        - pipenv run python setup.py test
