default:
    image: archlinux

stages:
    - setup
    - build
    - check
    - test

setup:
    stage: setup
    script:
        - pacman -Syu

build:
    stage: build
    script:
        - ls -lAh
