image: kennethreitz/pipenv

variables:
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/cache/.cache/"
    XDG_DATA_HOME: "$CI_PROJECT_DIR/cache/.local/share/"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - cache/

stages:
    - build
    - check
    - test

build:
    stage: build
    script:
        - ls -lAh cache || true
        - pipenv clean
        - pipenv sync --dev

check:
    stage: check
    script:
        - ls -lAh cache/.local/share/virtualenvs/mesh-city-TOfIyfl-/bin || true
        - pipenv run python -c "from subprocess import call; call(args=\"echo \$PATH\", shell=True)"
#        - pipenv shell "\
#        -     python setup.py imports_check && \
#        -     python setup.py format_check && \
#        -     python setup.py lint ; \
#        -     exit"
