image: kennethreitz/pipenv

variables:
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/cache/.cache/"
    XDG_DATA_HOME: "$CI_PROJECT_DIR/cache/.local/share/"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - cache/

stages:
    - build
    - check
    - test

build:
    stage: build
    script:
        - ls -lAh cache || true
        - pipenv clean
        - pipenv sync

check:
    stage: check
    script:
        - pipenv run python setup.py imports_check
        - pipenv run python setup.py format_check
        - pipenv run python setup.py lint
