default:
    image: archlinux/base

stages:
    - setup
    - build
    - check
    - test

setup:
    stage: setup
    script:
        - ping google.com

build:
    stage: build
    script:
        - ls -lAh
