image: kennethreitz/pipenv

stages:
    - build
    - check
    - test

build:
    stage: build
    script:
        - pipenv sync

check:
    stage: check
    script:
        - pipenv run python setup.py imports_check
        - pipenv run python setup.py format_check
        - pipenv run python setup.py lint
